//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace XaduxSite {
    
    
    public partial class _default {
        
        /// <summary>
        /// TopBandas_topBandas control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::XaduxSite.WebUserControls.TopBandas TopBandas_topBandas;
        
        /// <summary>
        /// EventosList_topEventos control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::XaduxSite.WebUserControls.EventosList EventosList_topEventos;
        
        /// <summary>
        /// TopMusicas_topMusicas control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::XaduxSite.WebUserControls.TopMusicas TopMusicas_topMusicas;
        
        /// <summary>
        /// NoticiasList_topNews control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::XaduxSite.WebUserControls.NoticiasList NoticiasList_topNews;
    }
}
